### ISSUE TITLE
How can use map to run projetc

### ISSUE THREAD

**Issue by ayoubelmhamdi** [CRAG666/code_runner.nvim#3]
the command `:SRunCode` open `json` configuration but has not started anything  
how can use `:RunCode` to start my project with this module

**Comment by CRAG666** [comment]
The plugin executes the file that is currently open, for its part the command: RunCode has been eliminated because previously python was used to achieve the execution but now pure lua is used, so if you want to assign some mapping you can do it through the setting passed to .setup, the default setting can be changed. For example, if you want to change the <leader> r command to something else, just specify it in the settings. I am currently working in project execution contexts.
